<template>
    <div v-if="showModal" class="modal-overlay" @click.self="closeModal">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title">
            <span class="material-symbols-outlined modal-title-logo">construction</span>
            <p>New Worker</p>
          </div>
        </div>
        <form class="modal-slot" @submit.prevent="createWorker">
          <!-- UID -->
          <input
            type="text"
            v-model="worker.uid"
            placeholder="UID (autogenerated)"
            disabled
          />  
          <!-- URI -->
          <input
            type="text"
            v-model="worker.uri"
            placeholder="Worker URI"
            required
          />
  
          <!-- API Key -->
          <input
            type="text"
            v-model="worker.apiKey"
            placeholder="API Key"
            required
          />  
          <div class="modal-form-btn">
            <button type="button" class="btn-cancel" @click="closeModal">
              Cancel
            </button>
            <button type="submit" class="btn-submit">Add</button>
          </div>
        </form>
      </div>
    </div>
</template>
  
<script>
import { ref } from "vue";
import Worker from "@/models/worker";
  
export default {
    props: {
        showModal: {
        type: Boolean,
        required: true,
        },
    },
    setup(props, { emit }) {
        const worker = ref(new Worker());

        const resetForm = () => {
        worker.value = new Worker();
        };

        const closeModal = () => {
        emit("close:cancel");
        resetForm();
        };

        const createWorker = () => {
        emit("close:create", worker.value);
        resetForm();
        };

        return {
        worker,
        closeModal,
        createWorker,
        };
    },
};
</script>
  
<style scoped>
.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1000;
}

.modal-content {
    background: white;
    padding: 2%;
    border-radius: 8px;
    width: 90%;
    max-width: 500px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
}

.modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.modal-title {
    font-size: x-large;
    font-weight: bold;
    display: flex;
    align-items: center;
}

.modal-title-logo {
    font-size: 200%;
    margin-right: 10px;
}

.modal-slot {
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.modal-slot input[type="text"] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: 3px solid #7e7d7d;
    transition: 0.5s;
    outline: none;
    background-color: white;
    color: black;
}

.modal-slot input:disabled {
    background-color: rgb(180, 180, 180);
}

.modal-slot input:focus {
    border: 3px solid #555;
}

.modal-form-btn {
    text-align: end;
}

.btn-cancel {
    background-color: red;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

.btn-submit {
    background-color: green;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    margin-left: 10px;
    cursor: pointer;
}
</style>
  